### PR TITLE
Build own docker image for raspberry pi

### PR DESCRIPTION
**Pull request by ardinusawan**
This PR to fix issue [here](https://github.com/SadeghHayeri/GreenTunnel/issues/61#issue-594404258)

### CODE REVIEW

**Comment by SadeghHayeri** [comment]
Thanks for your PR.
I will build and push your docker file with `arm` tag. can use change the build istructions to use `sadeghhayeri/green-tunnel:arm`?

**Comment by ardinusawan** [comment]
sure @SadeghHayeri

**Comment by ardinusawan** [comment]
Done @SadeghHayeri , please check

**Comment by SadeghHayeri** [comment]
Nice, please resolve the second discussion too.

**Comment by ardinusawan** [comment]
> Nice, please resolve the second discussion too.

@SadeghHayeri You mean [this](https://github.com/SadeghHayeri/GreenTunnel/issues/61)? Hm how to resolve ya? 🤔

**Comment by SadeghHayeri** [comment]
"
I think it's better to do not duplicate docker-file. Instead, insert this line (commented) under the main Dockerfile.
"

**Comment by ardinusawan** [comment]
Done @SadeghHayeri , please check

**Comment by SadeghHayeri** [comment]
I will merge your pull request after I build and push your docker file.
Thanks,

**Pull request merged**
